created:
    - database/factories/SyncErrorLogFactory.php
    - database/migrations/2025_05_12_045237_create_sync_error_logs_table.php
    - app/Models/SyncErrorLog.php
models:
    Journal: { external_id: 'integer unsigned', name: string, price: 'decimal:8,2', scope: json, path: string, thumbnail: string, publish_months: json, publisher_id: 'biginteger unsigned' }
    MessageLog: { channel: string, target: string, message: 'longtext nullable', media: 'string nullable', response: 'json nullable', success: boolean }
    Publisher: { publishing_name: string, address: 'text nullable', website: string, ojs_driver_url: string, user_id: 'biginteger unsigned' }
    User: { name: string, email: string, phone_number: 'string nullable', is_active: boolean, email_verified_at: 'timestamp nullable', password: string, remember_token: 'string:100 nullable' }
    SyncErrorLog: { external_id: 'unsignedInteger nullable', assoc: 'string nullable', payload: json, error_message: text }
